### PR TITLE
Update CoC with wording about external issues

### PR DESCRIPTION
**Pull request by ZacSweers**

### CODE REVIEW

**Comment by dannyroa** [comment]
👍

**Comment by cketti** [comment]
As a non-native speaker I find this hard to understand. Can you put it in simpler words?

**Comment by dlew** [comment]
How about: "If people raise issues with another member's treatment of them outside of ASG (including prior to their inclusion in ASG) the offending member may be removed."

**Comment by midiprincess** [comment]
What about something like "Because this Slack group is representative of the community, admins reserve the right to deny admission or revoke membership based on CoC violating behavior outside of the Slack chat environment (e.g. in person, GitHub, social media), if necessary."

**Comment by ZacSweers** [comment]
Sounds good to me

**Comment by ZacSweers** [comment]
I think we have a quorum after updating it with Haley's suggestion and internal feedback. @dannyroa want to merge?

**Pull request merged**
